CRITICAL - 2023-09-21 02:47:17 --> A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\total\total33.php on line 8.
 1 APPPATH\Views\total\total33.php(8): mysqli_connect('192.168.1.178', 'root', Object(SensitiveParameterValue), 'simrs')
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\total\\total33.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('total/total33', [], true)
 5 APPPATH\Views\kelas3.php(2804): view('total/total33')
 6 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\kelas3.php')
 7 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 8 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('kelas3', [], true)
 9 APPPATH\Views\detailpasien3.php(72): view('kelas3')
10 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\detailpasien3.php')
11 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
12 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('detailpasien3', [], true)
13 APPPATH\Controllers\DetailPasienController.php(4412): view('detailpasien3', [...])
14 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\DetailPasienController->kelas3()
15 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DetailPasienController))
16 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\public\\index.php')
CRITICAL - 2023-09-21 02:47:52 --> A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\total\total6.php on line 8.
 1 APPPATH\Views\total\total6.php(8): mysqli_connect('192.168.1.178', 'root', Object(SensitiveParameterValue), 'simrs')
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\total\\total6.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('total/total6', [], true)
 5 APPPATH\Views\kelas3.php(599): view('total/total6')
 6 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\kelas3.php')
 7 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 8 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('kelas3', [], true)
 9 APPPATH\Views\detailpasien3.php(72): view('kelas3')
10 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\detailpasien3.php')
11 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
12 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('detailpasien3', [], true)
13 APPPATH\Controllers\DetailPasienController.php(4412): view('detailpasien3', [...])
14 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\DetailPasienController->kelas3()
15 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DetailPasienController))
16 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\public\\index.php')
CRITICAL - 2023-09-21 02:48:27 --> A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\total\total14.php on line 8.
 1 APPPATH\Views\total\total14.php(8): mysqli_connect('192.168.1.178', 'root', Object(SensitiveParameterValue), 'simrs')
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\total\\total14.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('total/total14', [], true)
 5 APPPATH\Views\kelas3.php(1294): view('total/total14')
 6 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\kelas3.php')
 7 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 8 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('kelas3', [], true)
 9 APPPATH\Views\detailpasien3.php(72): view('kelas3')
10 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\detailpasien3.php')
11 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
12 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('detailpasien3', [], true)
13 APPPATH\Controllers\DetailPasienController.php(4412): view('detailpasien3', [...])
14 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\DetailPasienController->kelas3()
15 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DetailPasienController))
16 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\public\\index.php')
CRITICAL - 2023-09-21 03:05:19 --> A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\total\total.php on line 8.
 1 APPPATH\Views\total\total.php(8): mysqli_connect('192.168.1.178', 'root', Object(SensitiveParameterValue), 'simrs')
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\total\\total.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('total/total', [], true)
 5 APPPATH\Views\kelas3.php(211): view('total/total')
 6 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\kelas3.php')
 7 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 8 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('kelas3', [], true)
 9 APPPATH\Views\detailpasien3.php(72): view('kelas3')
10 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\detailpasien3.php')
11 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
12 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('detailpasien3', [], true)
13 APPPATH\Controllers\DetailPasienController.php(4412): view('detailpasien3', [...])
14 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\DetailPasienController->kelas3()
15 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DetailPasienController))
16 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\public\\index.php')
CRITICAL - 2023-09-21 03:05:47 --> A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\total\total37.php on line 8.
 1 APPPATH\Views\total\total37.php(8): mysqli_connect('192.168.1.178', 'root', Object(SensitiveParameterValue), 'simrs')
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\total\\total37.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('total/total37', [], true)
 5 APPPATH\Views\kelas3.php(3130): view('total/total37')
 6 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\kelas3.php')
 7 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 8 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('kelas3', [], true)
 9 APPPATH\Views\detailpasien3.php(72): view('kelas3')
10 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\detailpasien3.php')
11 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
12 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('detailpasien3', [], true)
13 APPPATH\Controllers\DetailPasienController.php(4412): view('detailpasien3', [...])
14 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\DetailPasienController->kelas3()
15 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DetailPasienController))
16 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\public\\index.php')
CRITICAL - 2023-09-21 04:10:45 --> A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\total\total30.php on line 8.
 1 APPPATH\Views\total\total30.php(8): mysqli_connect('192.168.1.178', 'root', Object(SensitiveParameterValue), 'simrs')
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\total\\total30.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('total/total30', [], true)
 5 APPPATH\Views\kelas3.php(2570): view('total/total30')
 6 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\kelas3.php')
 7 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 8 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('kelas3', [], true)
 9 APPPATH\Views\detailpasien3.php(72): view('kelas3')
10 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\detailpasien3.php')
11 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
12 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('detailpasien3', [], true)
13 APPPATH\Controllers\DetailPasienController.php(4412): view('detailpasien3', [...])
14 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\DetailPasienController->kelas3()
15 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DetailPasienController))
16 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\public\\index.php')
CRITICAL - 2023-09-21 04:11:22 --> A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\total\total9.php on line 8.
 1 APPPATH\Views\total\total9.php(8): mysqli_connect('192.168.1.178', 'root', Object(SensitiveParameterValue), 'simrs')
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\total\\total9.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('total/total9', [], true)
 5 APPPATH\Views\kelas1.php(847): view('total/total9')
 6 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\kelas1.php')
 7 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 8 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('kelas1', [], true)
 9 APPPATH\Views\detailpasien1.php(72): view('kelas1')
10 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\detailpasien1.php')
11 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
12 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('detailpasien1', [], true)
13 APPPATH\Controllers\DetailPasienController.php(1112): view('detailpasien1', [...])
14 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\DetailPasienController->kelas1()
15 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DetailPasienController))
16 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\public\\index.php')
ERROR - 2023-09-21 04:32:07 --> Error connecting to the database: mysqli_sql_exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('192.168.1.178', 'root', Object(SensitiveParameterValue), 'simrs', 3306, '', 0)
#1 C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\vendor\codeigniter4\framework\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\vendor\codeigniter4\framework\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\app\Models\DetailPasienModel.php(15): CodeIgniter\BaseModel->first()
#7 C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\app\Controllers\InsertCeklistController.php(1144): App\Models\DetailPasienModel->getDetailPasienData('007')
#8 C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(932): App\Controllers\InsertCeklistController->save3()
#9 C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\InsertCeklistController))
#10 C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp8.2.4\\h...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\vendor\codeigniter4\framework\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\vendor\codeigniter4\framework\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\app\Models\DetailPasienModel.php(15): CodeIgniter\BaseModel->first()
#6 C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\app\Controllers\InsertCeklistController.php(1144): App\Models\DetailPasienModel->getDetailPasienData('007')
#7 C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(932): App\Controllers\InsertCeklistController->save3()
#8 C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\InsertCeklistController))
#9 C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\vendor\codeigniter4\framework\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp8.2.4\htdocs\Clinicalpathway_Ci4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp8.2.4\\h...')
#12 {main}
CRITICAL - 2023-09-21 04:32:07 --> Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `t_clinicalpathway`
WHERE `NOMR` = :NOMR:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\DetailPasienModel.php(15): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\InsertCeklistController.php(1144): App\Models\DetailPasienModel->getDetailPasienData('007')
 7 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\InsertCeklistController->save3()
 8 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\InsertCeklistController))
 9 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\public\\index.php')
CRITICAL - 2023-09-21 04:33:28 --> A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\total\total8.php on line 8.
 1 APPPATH\Views\total\total8.php(8): mysqli_connect('192.168.1.178', 'root', Object(SensitiveParameterValue), 'simrs')
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\total\\total8.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('total/total8', [], true)
 5 APPPATH\Views\kelas3.php(765): view('total/total8')
 6 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\kelas3.php')
 7 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 8 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('kelas3', [], true)
 9 APPPATH\Views\detailpasien3.php(72): view('kelas3')
10 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\detailpasien3.php')
11 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
12 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('detailpasien3', [], true)
13 APPPATH\Controllers\DetailPasienController.php(4412): view('detailpasien3', [...])
14 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\DetailPasienController->kelas3()
15 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DetailPasienController))
16 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\public\\index.php')
CRITICAL - 2023-09-21 04:34:18 --> A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\total\total30.php on line 8.
 1 APPPATH\Views\total\total30.php(8): mysqli_connect('192.168.1.178', 'root', Object(SensitiveParameterValue), 'simrs')
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\total\\total30.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('total/total30', [], true)
 5 APPPATH\Views\kelas3.php(2570): view('total/total30')
 6 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\kelas3.php')
 7 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 8 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('kelas3', [], true)
 9 APPPATH\Views\detailpasien3.php(72): view('kelas3')
10 SYSTEMPATH\View\View.php(224): include('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\app\\Views\\detailpasien3.php')
11 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
12 SYSTEMPATH\Common.php(1176): CodeIgniter\View\View->render('detailpasien3', [], true)
13 APPPATH\Controllers\DetailPasienController.php(4412): view('detailpasien3', [...])
14 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\DetailPasienController->kelas3()
15 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DetailPasienController))
16 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp8.2.4\\htdocs\\Clinicalpathway_Ci4\\public\\index.php')
